version: "3"

services:
  e621-utils:
    image: ghcr.io/donovandmc/e621utils
    container_name: e621-utils
    volumes:
      - ./data:/mnt/data
      - ./config.json:/app/config.json
    restart: always
    init: true
    healthcheck:
      interval: 5s
      timeout: 1s
      test: wget -q --spider http://localhost:3621
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    hostname: e621-utils.containers.local
    networks:
      default:
        ipv4_address: 172.19.1.34

networks:
  default:
    name: e621-utils
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.1.32/30
          gateway: 172.19.1.33
